max_vel_lin: 0.5                        # default : 0.74
max_vel_th: 0.4                         # default : 0.5

min_vel_lin: 0.1                        # default : 0.1
min_vel_th: 0.0                         # default : 0.0

min_in_place_vel_th: 0.0                # default : 0.0
in_place_trans_vel: 0.0                 # default : 0.0

xy_goal_tolerance: 0.02                 # default : 0.08
yaw_goal_tolerance: 0.04                # default : 0.1
tolerance_timeout: 0.5                  # default : 0.5

k_prop: 3.0                             # default : 4.0
k_damp: 3.5                             # default : 3.5

Ctrl_Rate: 15.0                         # default : 15.0

max_acceleration: 0.2                   # default : 0.3
virtual_mass: 0.75                      # default : 0.75

max_translational_acceleration: 0.2     # default : 0.3
max_rotational_acceleration: 1.0        # default : 1.5

rotation_correction_threshold: 2.0      # default : 2.0
