#!/usr/bin/env python

import mcr_relative_base_controller_ros.direct_base_controller_coordinator

if __name__ == '__main__':
    mcr_relative_base_controller_ros.direct_base_controller_coordinator.main()
