#!/usr/bin/python

import rospy
import geometry_msgs
from mcr_navigation_msgs.srv import MoveRelative, MoveRelativeResponse
import std_srvs.srv
import tf

def DoService(req):

    ret = MoveRelativeResponse()
    return ret

def init_server():
    rospy.init_node('move_base_relative_mockup')
    s = rospy.Service('~move_base_relative', MoveRelative, DoService)
    print "move_base_relative MOCKUP ready..."
    rospy.spin()

if __name__ == "__main__":
    init_server()

